# Generated by Django 5.0.2 on 2024-10-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile_numeber',
            new_name='mobile_number',
        ),
    ]
